name: On Push
on:
  push:
    branches:
      - main
    paths:
      - app/**
      - tests/**
      - uv.lock
      - pyproject.toml
      - .github/workflows/on_push.yaml

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv run --frozen poe unit
        shell: bash
  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv run --frozen poe integration
  e2e:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv run --frozen poe setup_ollama
      - run: sudo chown -R $USER /usr/share/ollama/
      - id: cache-llm
        uses: actions/cache@v4
        with:
          path: /usr/share/ollama/.ollama/models
          key: ${{ runner.os }}-llm
      - run: sudo chown -R ollama:ollama /usr/share/ollama/
      - run: uv run --frozen poe setup_llm
        if: steps.cache-llm.outputs.cache-hit != 'true'
      - id: cache-browser
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/ms-playwright
          key: ${{ runner.os }}-browser
      - run: uv run --frozen poe setup_browser
      - run: uv run --frozen poe e2e
