name: On Push
on:
  push:
    branches:
      - main
    paths:
      - app/**
      - test/**
      - uv.lock
      - pyproject.toml
      - .github/workflows/on_push.yaml

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv run --frozen poe unit
        shell: bash
  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: uv run --frozen poe integration
  e2e:
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - run: curl -fsSL https://ollama.com/install.sh | sh
      - run: ollama pull gemma2:2b
      - run: uv run --frozen poe setup_e2e
      - run: uv run --frozen poe e2e
